vich_uploader:
    db_driver: orm

    mappings:
        model_image:
            uri_prefix: /images/models
            upload_destination: '%kernel.project_dir%/public/images/models'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
